name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: serious-conduit-448301-d7
  SERVICE_NAME: ltx-video-api
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ./cloudrun
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --memory 16Gi \
          --cpu 4 \
          --gpu 1 \
          --gpu-type nvidia-l4 \
          --max-instances 3 \
          --timeout 3600 \
          --set-env-vars GOOGLE_CLOUD_PROJECT=${{ env.PROJECT_ID }} \
          --set-env-vars MODEL_BUCKET=tomi-ltx-models-1760477322 \
          --set-env-vars OUTPUT_BUCKET=tomi-ltx-videos \
          --service-account ltx-video-service@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
    
    - name: Test deployment
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')
        echo "Service URL: $SERVICE_URL"
        
        # Health check
        curl -f "$SERVICE_URL/health" || exit 1
        
        echo "✅ Deployment successful!"
        echo "🔗 Service URL: $SERVICE_URL"
